apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JscDIyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3JscDIyIiwicGFzc3dvcmQiOiJTWFByY0FNNFdxMHJXTGZuYk9SZTRTditQeWFjMDhQbiIsImF1dGgiOiJZV055YkhBeU1qcFRXRkJ5WTBGTk5GZHhNSEpYVEdadVlrOVNaVFJUZGl0UWVXRmpNRGhRYmc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2023-01-06T13:46:27Z"
  name: acr-secret5
  namespace: erwan-ns
  resourceVersion: "1097810"
  uid: 84a8a5fc-b025-4b4b-8e5c-fa04fad69fab
type: kubernetes.io/dockerconfigjson