apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rest-api
spec:
  replicas: {{ .Values.RestAPI.replicas }}
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: apiv1
        image: acrlp22.azurecr.io/promeoapi:v1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: configmap-rest-api
            mountPath: /rest-api/rest-api.json
            subPath: rest-api.json
      volumes:
        - name: configmap-rest-api
          configMap:
            name: configmap-rest-api
      imagePullSecrets:
        - name: acrlp22.azurecr.io