apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: apiv1
        image: acrlp22.azurecr.io/promeoapi:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acrlp22.azurecr.io