kind: Secret
apiVersion: v1
metadata:
  name: acr-secret
  namespace: default
type: Opaque
data:
  docker-server: acrlp22.azurecr.io
  docker-username: acrlp22
  docker-password: SXPrcAM4Wq0rWLfnbORe4Sv+Pyac08Pn