apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JscDIyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3JscDIyIiwicGFzc3dvcmQiOiJTWFByY0FNNFdxMHJXTGZuYk9SZTRTditQeWFjMDhQbiIsImF1dGgiOiJZV055YkhBeU1qcFRXRkJ5WTBGTk5GZHhNSEpYVEdadVlrOVNaVFJUZGl0UWVXRmpNRGhRYmc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2023-01-06T13:03:18Z"
  name: acrlp22.azurecr.io
  namespace: thomas-clement
type: kubernetes.io/dockerconfigjson