name: K8S_Helm_deployment

trigger: 
- thomas-clement

pool:
  vmImage: ubuntu-latest

stages:
- stage: Package
  displayName: "Package"

  jobs:
  - job: Package
    displayName: "Package"
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: chart'
      inputs:
        PathtoPublish: https://github.com/tcharrier/lp23helm/tree/thomas-clement/chart
        ArtifactName: rest-api
    - task: CreateNamespace@1
      inputs:
        command: kubectl create namespace dev-thomas-clement
    - task: CreateNamespace@2
      inputs:
        command: kubectl create namespace prod-thomas-clement

- stage: DEV
  dependsOn: Package
  displayName: "DEV"
  jobs:
  - deployment:
    environment: dev 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: rest-api
              downloadPath: '$(Pipeline.Workspace)'
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'AZURE_PROMEO'
              azureResourceGroup: '2023_promeo'
              kubernetesCluster: lp2023
              namespace: dev-thomas-clement
              command: upgrade
              chartType: FilePath
              chartPath: $(Pipeline.Workspace)/chart
              valueFile: 'RestAPI.version=dev'
              releaseName: dev
              force: true

- stage: PROD
  dependsOn: DEV
  displayName: "PROD"
  jobs:
  - deployment:
    environment: prod 
    strategy:
      runOnce:              
        deploy:    
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: rest-api
              downloadPath: '$(Pipeline.Workspace)'
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'AZURE_PROMEO'
              azureResourceGroup: '2023_Promeo_2'
              kubernetesCluster: 'lp2023_1'
              namespace: prod-thomas-clement
              command: upgrade
              chartType: FilePath
              chartPath: $(Pipeline.Workspace)/chart
              valueFile: 'RestAPI.version=prod'
              releaseName: prod
              force: true
